

default: CompileAll

CompileAll:
	(cd CommonCode && make)
	(cd V22Processing && make)
	(cd Efficiency && make)
	(cd TurnOnScaling && make)

CleanAll:
	(cd CommonCode && make Clean)
	(cd V22Processing && make Clean)
	(cd Efficiency && make Clean)
	(cd TurnOnScaling && make Clean)



